name: Secrets Workflow

on:
  workflow_dispatch: 

env:
  API_CSPROJ_PATH: "src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"
    steps:
      - name: echo environment variables
        run: |
          echo $JOB_NAME
          echo "$API_CSPROJ_PATH"
  new_job:
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "new job"
    steps:
      - name: echo environment variables
        run: |
          echo $JOB_NAME
          echo SECRET KEY: "${{secrets.SECRET_API_KEY}}}"

